# Generated by Django 6.1.1 on 2026-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpverification_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
